### ISSUE TITLE
動かない

### ISSUE THREAD

**Issue by Animenosekai** [theoria24/searchGguide#17]
`ruby main.rb  -f "%Y/%m/%d(%a) %H:%M" <keyword>`で開いているのですが、プログレスバーが0%のまま動きません。
Line 64の所に`puts url`を入れたのですが、`https://tv.yahoo.co.jp/api/adapter?query=選択したキーワード&siTypeId=3&areaId=10&start=0`と表示して、`start`パラメーターが１秒ごとに変化するのですが何も起こりません。

Pythonやブラウザで開いたら、JSONの回答でなく、`お探しのページは見つかりませんでした。`と表示されます。

APIの問題ですか？それとも打ってるコマンドの問題ですか？

ルビーのバージョンは `ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.arm64e-darwin20]` です。
OSは`macOS Big Sur (11.0.1)`です

**Comment by theoria24** [comment]
APIの取得方法が変わったようで、現状だと常に10件取得され、次のページを取得しようとするのを繰り返している状況のようです。（検索ワード等も効いておらずあらゆる番組がヒットする結果が返ってくる？）

リニューアル途中のようなのでまた変わる可能性がありますね……対応しますがしばらくお待ち下さい…

Python等の件はおそらくヘッダーに`target-api: mindsSiQuery`が必要です。

**Comment by Animenosekai** [comment]
その後、僕もヤフーさんのAPIをちょっと検査した結果、ヘッダーが足りなかったのを知りました（自分もPython用のゲートウェイを作ろうと思って）

返信ありがとうございました！
